name: Main
on:
  push:
    branches:
      - "main"
      - "demo"
permissions:
  contents: read
  pull-requests: write
env:
  ENVIRONMENT_ID: 'development'
  SCORE_HUMANITEC_VERSION: 0.10.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push to Humanitec
        id: build-push
        uses: humanitec/build-push-to-humanitec@v1
        with:
          humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
          organization: ${{ vars.HUMANITEC_ORG }}
      - name: Install score-humanitec
        run: |
          wget https://github.com/score-spec/score-humanitec/releases/download/${{ env.SCORE_HUMANITEC_VERSION }}/score-humanitec_${{ env.SCORE_HUMANITEC_VERSION }}_linux_amd64.tar.gz
          tar -xvf score-humanitec_${{ env.SCORE_HUMANITEC_VERSION }}_linux_amd64.tar.gz
          chmod +x score-humanitec
          mv score-humanitec /usr/local/bin
      - name: Run Score
        run: |
          if ! [ -f score.yaml ]
          then 
            echo "no score file found, cannot deploy"
            exit 1
          fi
          score-humanitec delta \
              --image "${{ steps.build-push.outputs.image }}" \
              --retry \
              --deploy \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ vars.HUMANITEC_ORG }} \
              --app ${{ vars.HUMANITEC_APP }} \
              --env ${{ env.ENVIRONMENT_ID }} > score_output.json
